### ISSUE TITLE
`MinAlertLevel = suggestion` causes flycheck-vale to break

### ISSUE THREAD

**Issue by mrcnski** [abingham/flycheck-vale#12]
This package doesn't work with this in my `.vale.ini`:

```ini
MinAlertLevel = suggestion # suggestion, warning or error
```

```
error in process sentinel: flycheck-add-overlay: Undefined error level: nil
error in process sentinel: Undefined error level: nil
```

It works again once I set the minimum level to `warning`.

**Comment by abingham** [comment]
I'm not actively maintaining this any more (I've switched away from Emacs), but I'd be happy to help you (or anyone) take over if you're so inclined.

**Comment by juergenhoetzel** [comment]
> I'm not actively maintaining this any more (I've switched away from Emacs), but I'd be happy to help you (or anyone) take over if you're so inclined.

#14 works for me nice! :+1:

**Comment by juergenhoetzel** [comment]
> I'm not actively maintaining this any more (I've switched away from Emacs)

Thank you for inviting me as a collaborator. I suspect that we lost you to VSCode. But I hope/suspect you return to Emacs sooner than later :smile:
