### ISSUE TITLE
Can't get any errors

### ISSUE THREAD

**Issue by andreyorst** [abingham/flycheck-vale#16]
When I run `vale` from command line on some markdown files, I see a list of errors in stdout. However in Emacs flycheck reports no errors.

What additional info should I attach here? `*Messages*` buffer has no errors, and flycheck doesn't seem to show any warnings either.

**Comment by abingham** [comment]
I'm not really using or supporting this project any more, but it may be that vale has changed its output format.

**Comment by andreyorst** [comment]
understood. I'll try to fix this and submit PR later this week if you don't mind
