### ISSUE TITLE
Undefined symbols

### ISSUE THREAD

**Issue by zovt** [abingham/flycheck-vale#4]
Hey, just installed this and tried it out. However, I am presented with an error when trying to lint: 
```
Symbol's function definition is void: concatenate
```

**Comment by abingham** [comment]
Oops, sorry. I think `concatenate` is obsolete or something. I've updated the code to use `append` instead. Give it a shot now and let me know if it works.

**Comment by zovt** [comment]
`Symbol's function definition is void: loop`

**Comment by zovt** [comment]
Thanks for the quick response! :)

**Comment by abingham** [comment]
NP, I'm glad to see people use this...just wished I'd pushed up all the necessary fixes :)

Anyhow, I've pushed up a new change that should fix the `loop` issue. Try it now.

And sorry for the confusion. I'm a half-assed emacs-lisp programmer at best, and I don't always know the proper functions to use, what's been deprecated, etc. It's a bit of a zoo.

**Comment by zovt** [comment]
>I'm a half-assed emacs-lisp programmer at best

I'm fairly certain you wrote emacs-ycmd, so I wouldn't say that :)

Looks like everything is good now! Thanks :D

**Comment by abingham** [comment]
Cool, I'm glad it works!
